# Breast Cancer Binary Classification

In [1]:
import pandas as pd

from keras import layers, backend, Sequential
from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import GridSearchCV, cross_val_score

from functools import partial

## Load Datasets

In [2]:
X = pd.read_csv("datasets/cancer-features.csv")
y = pd.read_csv("datasets/cancer-target.csv")

display(X)
display(y)

     radius_mean   texture_mean  ...   symmetry_worst   fractal_dimension_worst
0          17.99          10.38  ...           0.4601                   0.11890
1          20.57          17.77  ...         275.0000                   0.08902
2          19.69          21.25  ...           0.3613                   0.08758
3          11.42          20.38  ...           0.6638                 173.00000
4          20.29          14.34  ...           0.2364                   0.07678
..           ...            ...  ...              ...                       ...
564        21.56          22.39  ...         206.0000                   0.07115
565        20.13          28.25  ...           0.2572                   0.06637
566        16.60          28.08  ...           0.2218                   0.07820
567        20.60          29.33  ...           0.4087                 124.00000
568         7.76          24.54  ...           0.2871                   0.07039

[569 rows x 30 columns]

     benign
0         0
1         0
2         0
3         0
4         0
..      ...
564       0
565       0
566       0
567       0
568       1

[569 rows x 1 columns]

## Neural Network

### Definition

In [3]:
def get_neural_network(
    units:int,
    activation:str,
    kernel_initializer:str,
    optimizer:str,
    loss:str,
) -> Sequential:
    backend.clear_session()

    model = Sequential()
    model.add(layers.InputLayer(shape=(30,)))
    model.add(layers.Dense(units=units, activation=activation, kernel_initializer=kernel_initializer))
    model.add(layers.Dropout(rate=0.2))
    model.add(layers.Dense(units=units, activation=activation, kernel_initializer=kernel_initializer))
    model.add(layers.Dropout(rate=0.2))
    model.add(layers.Dense(units=1, activation='sigmoid', kernel_initializer=kernel_initializer))

    model.compile(
        optimizer=optimizer,
        loss=loss,
        metrics=['binary_accuracy']
    )

    return model

model = KerasClassifier(model=get_neural_network, verbose=0)

### Tuning

In [ ]:
params = {
    'batch_size': [10, 30],
    'epochs': [50, 100],
    'model__units': [8, 16], 
    'model__activation': ['relu', 'tanh'],
    'model__kernel_initializer': ['random_uniform', 'normal'],
    'model__optimizer': ['adam', 'sgd'],
    'model__loss': ['binary_crossentropy']
}

tuning_results = GridSearchCV(
    estimator=model,
    param_grid=params,
    scoring='accuracy',
    cv=5,
    verbose=2
).fit(X, y) # 56 min

In [ ]:
print(tuning_results.best_params_) # {'batch_size': 10, 'epochs': 100, 'model__activation': 'relu', 'model__kernel_initializer': 'normal', 'model__loss': 'binary_crossentropy', 'model__optimizer': 'adam', 'model__units': 8}
print(tuning_results.best_score_) # 0.9086787765874865

### Best model evaluation

In [7]:
best_model = KerasClassifier(
    model = partial(
        get_neural_network,
        units=8,
        activation='relu',
        kernel_initializer='normal',
        optimizer='adam',
        loss='binary_crossentropy'
    ),
    epochs=100,
    batch_size=10,
    verbose=0
)

results = cross_val_score(
    estimator=best_model,
    X=X, y=y,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

In [8]:
print(f"Accuracies: {results}")
print(f"Mean: {results.mean()}, Std: {results.std()}")

Accuracies: [0.80701754 0.89473684 0.94736842 0.93859649 0.89380531]
Mean: 0.8963049215960254, Std: 0.04975339303903367

## Final Model

### Fit with All Samples

In [9]:
classificator = KerasClassifier(
    model = partial(
        get_neural_network,
        units=8,
        activation='relu',
        kernel_initializer='normal',
        optimizer='adam',
        loss='binary_crossentropy'
    ),
    epochs=100,
    batch_size=10
).fit(
    X=X,
    y=y
)

Epoch 1/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - binary_accuracy: 0.4763 - loss: 0.7593
Epoch 2/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6116 - loss: 0.6551
Epoch 3/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6344 - loss: 0.6244
Epoch 4/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6608 - loss: 0.5950
Epoch 5/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7100 - loss: 0.5693
Epoch 6/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7030 - loss: 0.5395
Epoch 7/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7417 - loss: 0.4929
Epoch 8/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7329 - loss: 0.5202
Epoch 9/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7610 - loss: 0.4967
Epoch 10/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7891 - loss: 0.4596
Epoch 11/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7891 - loss: 0.4696
Epoch 12/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8014 - loss: 0.4506
Epoch 13/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8207 - loss: 0.4357
Epoch 14/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8084 - loss: 0.4370
Epoch 15/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8295 - loss: 0.4055
Epoch 16/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8313 - loss: 0.3961
Epoch 17/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8137 - loss: 0.4059
Epoch 18/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8471 - loss: 0.3675
Epoch 19/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8770 - loss: 0.3246
Epoch 20/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8682 - loss: 0.3399
Epoch 21/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8805 - loss: 0.3151
Epoch 22/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8910 - loss: 0.3129
Epoch 23/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8963 - loss: 0.2891
Epoch 24/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8858 - loss: 0.2788
Epoch 25/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8946 - loss: 0.2823
Epoch 26/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8805 - loss: 0.3092
Epoch 27/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8787 - loss: 0.3088
Epoch 28/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8699 - loss: 0.3031
Epoch 29/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8822 - loss: 0.3020
Epoch 30/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9016 - loss: 0.2820
Epoch 31/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8875 - loss: 0.2831
Epoch 32/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8998 - loss: 0.2973
Epoch 33/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9069 - loss: 0.2758
Epoch 34/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9086 - loss: 0.2351
Epoch 35/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8998 - loss: 0.2610
Epoch 36/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8981 - loss: 0.2607
Epoch 37/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8998 - loss: 0.2413
Epoch 38/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8910 - loss: 0.2516
Epoch 39/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8998 - loss: 0.2569
Epoch 40/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8875 - loss: 0.2815
Epoch 41/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8998 - loss: 0.2482
Epoch 42/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8998 - loss: 0.2505
Epoch 43/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9104 - loss: 0.2367
Epoch 44/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9104 - loss: 0.2371
Epoch 45/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9033 - loss: 0.2331
Epoch 46/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8928 - loss: 0.2431
Epoch 47/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9051 - loss: 0.2502
Epoch 48/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9121 - loss: 0.2280
Epoch 49/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9139 - loss: 0.2257
Epoch 50/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9121 - loss: 0.2253
Epoch 51/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9086 - loss: 0.2152
Epoch 52/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9033 - loss: 0.2410
Epoch 53/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9033 - loss: 0.2355
Epoch 54/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9244 - loss: 0.2095
Epoch 55/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9297 - loss: 0.1988
Epoch 56/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8963 - loss: 0.2464
Epoch 57/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9192 - loss: 0.1983
Epoch 58/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9262 - loss: 0.2132
Epoch 59/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8998 - loss: 0.2345
Epoch 60/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9033 - loss: 0.2289
Epoch 61/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9121 - loss: 0.2034
Epoch 62/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9139 - loss: 0.2023
Epoch 63/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9139 - loss: 0.2004
Epoch 64/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.9244 - loss: 0.2074
Epoch 65/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9209 - loss: 0.1858
Epoch 66/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9139 - loss: 0.1954
Epoch 67/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9192 - loss: 0.1900
Epoch 68/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9227 - loss: 0.1941
Epoch 69/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9156 - loss: 0.2102
Epoch 70/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9262 - loss: 0.2002
Epoch 71/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9244 - loss: 0.1915
Epoch 72/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9262 - loss: 0.1968
Epoch 73/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9227 - loss: 0.2215
Epoch 74/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9262 - loss: 0.1798
Epoch 75/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9244 - loss: 0.2044
Epoch 76/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9244 - loss: 0.1965
Epoch 77/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9315 - loss: 0.1880
Epoch 78/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9297 - loss: 0.1844
Epoch 79/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9244 - loss: 0.1955
Epoch 80/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9192 - loss: 0.2040
Epoch 81/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8928 - loss: 0.2343
Epoch 82/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9227 - loss: 0.1944
Epoch 83/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9227 - loss: 0.1847
Epoch 84/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8998 - loss: 0.2173
Epoch 85/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8998 - loss: 0.2193
Epoch 86/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9279 - loss: 0.1837
Epoch 87/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.9192 - loss: 0.2016
Epoch 88/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9069 - loss: 0.2133
Epoch 89/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9069 - loss: 0.2070
Epoch 90/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9104 - loss: 0.2312
Epoch 91/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9174 - loss: 0.2014
Epoch 92/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9297 - loss: 0.1883
Epoch 93/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9209 - loss: 0.1960
Epoch 94/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9244 - loss: 0.1852
Epoch 95/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9262 - loss: 0.1961
Epoch 96/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9174 - loss: 0.2068
Epoch 97/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9262 - loss: 0.1826
Epoch 98/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9279 - loss: 0.1926
Epoch 99/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9174 - loss: 0.2113
Epoch 100/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9227 - loss: 0.2053

### Save the Model

In [10]:
classificator.model_.save('models/classificator.keras')